name:                dotf
version:             3.0.0.0
github:              "abjoru/dotf-v3"
license:             BSD-3-Clause
author:              "Andreas Bjoru"
maintainer:          "andreas.bjoru@gmail.com"
copyright:           "2024 Andreas Bjoru"

extra-source-files:
- README.md

description:         Modular dotfile manager with git bare repo + sparse checkout

dependencies:
- base
- extra
- bytestring
- typed-process
- directory
- filepath
- string-interpolate
- process
- text
- yaml
- aeson
- microlens
- microlens-mtl
- microlens-th
- mtl
- vector
- optparse-applicative
- containers
- brick
- vty
- text-zipper
- async

default-extensions:
- OverloadedStrings
- TemplateHaskell
- QuasiQuotes

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-imports
- -Werror

library:
  source-dirs: src

executables:
  dotf:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    dependencies:
    - dotf

tests:
  dotf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dotf
    - hspec
    - hspec-discover
    - hedgehog
    - hspec-hedgehog
